/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedDashboardSettingsRouteImport } from './routes/_authed/dashboard/settings'
import { Route as AuthedDashboardDocumentsIndexRouteImport } from './routes/_authed/dashboard/documents/index'
import { Route as AuthedDashboardDocumentsPinnedRouteImport } from './routes/_authed/dashboard/documents/pinned'
import { Route as AuthedDashboardDocumentsDeletedRouteImport } from './routes/_authed/dashboard/documents/deleted'
import { Route as AuthedDashboardDocumentDoc_idRouteImport } from './routes/_authed/dashboard/document/$doc_id'
import { Route as AuthedDashboardDocumentDeletedDoc_idRouteImport } from './routes/_authed/dashboard/document/deleted/$doc_id'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardSettingsRoute = AuthedDashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardDocumentsIndexRoute =
  AuthedDashboardDocumentsIndexRouteImport.update({
    id: '/dashboard/documents/',
    path: '/dashboard/documents/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardDocumentsPinnedRoute =
  AuthedDashboardDocumentsPinnedRouteImport.update({
    id: '/dashboard/documents/pinned',
    path: '/dashboard/documents/pinned',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardDocumentsDeletedRoute =
  AuthedDashboardDocumentsDeletedRouteImport.update({
    id: '/dashboard/documents/deleted',
    path: '/dashboard/documents/deleted',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardDocumentDoc_idRoute =
  AuthedDashboardDocumentDoc_idRouteImport.update({
    id: '/dashboard/document/$doc_id',
    path: '/dashboard/document/$doc_id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardDocumentDeletedDoc_idRoute =
  AuthedDashboardDocumentDeletedDoc_idRouteImport.update({
    id: '/dashboard/document/deleted/$doc_id',
    path: '/dashboard/document/deleted/$doc_id',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/document/$doc_id': typeof AuthedDashboardDocumentDoc_idRoute
  '/dashboard/documents/deleted': typeof AuthedDashboardDocumentsDeletedRoute
  '/dashboard/documents/pinned': typeof AuthedDashboardDocumentsPinnedRoute
  '/dashboard/documents': typeof AuthedDashboardDocumentsIndexRoute
  '/dashboard/document/deleted/$doc_id': typeof AuthedDashboardDocumentDeletedDoc_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/dashboard/document/$doc_id': typeof AuthedDashboardDocumentDoc_idRoute
  '/dashboard/documents/deleted': typeof AuthedDashboardDocumentsDeletedRoute
  '/dashboard/documents/pinned': typeof AuthedDashboardDocumentsPinnedRoute
  '/dashboard/documents': typeof AuthedDashboardDocumentsIndexRoute
  '/dashboard/document/deleted/$doc_id': typeof AuthedDashboardDocumentDeletedDoc_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authed/dashboard/settings': typeof AuthedDashboardSettingsRoute
  '/_authed/dashboard/document/$doc_id': typeof AuthedDashboardDocumentDoc_idRoute
  '/_authed/dashboard/documents/deleted': typeof AuthedDashboardDocumentsDeletedRoute
  '/_authed/dashboard/documents/pinned': typeof AuthedDashboardDocumentsPinnedRoute
  '/_authed/dashboard/documents/': typeof AuthedDashboardDocumentsIndexRoute
  '/_authed/dashboard/document/deleted/$doc_id': typeof AuthedDashboardDocumentDeletedDoc_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/settings'
    | '/dashboard/document/$doc_id'
    | '/dashboard/documents/deleted'
    | '/dashboard/documents/pinned'
    | '/dashboard/documents'
    | '/dashboard/document/deleted/$doc_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/settings'
    | '/dashboard/document/$doc_id'
    | '/dashboard/documents/deleted'
    | '/dashboard/documents/pinned'
    | '/dashboard/documents'
    | '/dashboard/document/deleted/$doc_id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/_authed/dashboard/settings'
    | '/_authed/dashboard/document/$doc_id'
    | '/_authed/dashboard/documents/deleted'
    | '/_authed/dashboard/documents/pinned'
    | '/_authed/dashboard/documents/'
    | '/_authed/dashboard/document/deleted/$doc_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/settings': {
      id: '/_authed/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedDashboardSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/documents/': {
      id: '/_authed/dashboard/documents/'
      path: '/dashboard/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof AuthedDashboardDocumentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/documents/pinned': {
      id: '/_authed/dashboard/documents/pinned'
      path: '/dashboard/documents/pinned'
      fullPath: '/dashboard/documents/pinned'
      preLoaderRoute: typeof AuthedDashboardDocumentsPinnedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/documents/deleted': {
      id: '/_authed/dashboard/documents/deleted'
      path: '/dashboard/documents/deleted'
      fullPath: '/dashboard/documents/deleted'
      preLoaderRoute: typeof AuthedDashboardDocumentsDeletedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/document/$doc_id': {
      id: '/_authed/dashboard/document/$doc_id'
      path: '/dashboard/document/$doc_id'
      fullPath: '/dashboard/document/$doc_id'
      preLoaderRoute: typeof AuthedDashboardDocumentDoc_idRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/document/deleted/$doc_id': {
      id: '/_authed/dashboard/document/deleted/$doc_id'
      path: '/dashboard/document/deleted/$doc_id'
      fullPath: '/dashboard/document/deleted/$doc_id'
      preLoaderRoute: typeof AuthedDashboardDocumentDeletedDoc_idRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardSettingsRoute: typeof AuthedDashboardSettingsRoute
  AuthedDashboardDocumentDoc_idRoute: typeof AuthedDashboardDocumentDoc_idRoute
  AuthedDashboardDocumentsDeletedRoute: typeof AuthedDashboardDocumentsDeletedRoute
  AuthedDashboardDocumentsPinnedRoute: typeof AuthedDashboardDocumentsPinnedRoute
  AuthedDashboardDocumentsIndexRoute: typeof AuthedDashboardDocumentsIndexRoute
  AuthedDashboardDocumentDeletedDoc_idRoute: typeof AuthedDashboardDocumentDeletedDoc_idRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardSettingsRoute: AuthedDashboardSettingsRoute,
  AuthedDashboardDocumentDoc_idRoute: AuthedDashboardDocumentDoc_idRoute,
  AuthedDashboardDocumentsDeletedRoute: AuthedDashboardDocumentsDeletedRoute,
  AuthedDashboardDocumentsPinnedRoute: AuthedDashboardDocumentsPinnedRoute,
  AuthedDashboardDocumentsIndexRoute: AuthedDashboardDocumentsIndexRoute,
  AuthedDashboardDocumentDeletedDoc_idRoute:
    AuthedDashboardDocumentDeletedDoc_idRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
